If you're reading this document than you have most likely signed up for my course "Getting Started
with Spring Boot 2". I want to thank you for supporting me and taking the time to invest
in yourself. I hope you enjoy this course and if you have any questions please feel free to
<<index.adoc#_contact_me,contact me>>.

=== About
This course offers hands-on experience building Spring Framework applications using Spring Boot. The first thing that is going to stand out is that we are going to move away from the boring, non-useful demos. In the new course, we are going to build a practical application from start to finish. This will allow you to see the process I use for building applications from idea to launch.

One of the big thing I heard from my students in my first course is that they wanted more information on how to go into production. A great application isn’t that useful if we can deploy it into a production environment. We will take a look at using one of the most popular cloud services around, Amazon Web Services (AWS). On completion, students will have the foundation they need to build enterprise-ready Java applications.

=== Prerequisites
* Java Developer
* Web Development
* Git & Github
* Heard of Spring Framework & Spring Boot
* You want to see some of the new features in:
    ** Spring Framework 5
    ** Spring Boot 2.0

=== Requirements
* Java 9
* Mac OS / Windows / Linux

=== Curriculum
* Introduction
    ** Course Introduction
    ** Goals for this course
    ** Development Environment Setup
    ** Course Documentation
    ** Spring Framework vs Spring Boot
* Project Overview
    ** Introduction
    ** Create the Initial Project
    ** Running with Spring Boot
    ** Requirements
    ** UI Intro
    ** UI Templates
    ** Domain Model
* Github
    ** Introduction
    ** Create the initial repository
    ** README setup
    ** Branching strategy
* Spring Boot Essentials
    ** Introduction
    ** Spring Boot devtools
    ** Configuration & Properties
    ** Profiles
    ** Debugging & Logging
    ** Actuator
* Spring MVC: Model
    ** Spring Data JPA Introduction
    ** Link Entity & Repository
    ** Project Lombok Refactor
    ** Comment & Vote Entities
    ** Auditing Aware
* Database Layer
    ** Properties
    ** H2 in memory database setup
    ** Creating data using SQL
    ** Creating data using Java

=== Course Project



=== Course Assets
// we may want to put this behind a email signup form
If we need to provide a download this would be a great place to link to those assets.
