= Getting Started with Spring Boot 2.0
Dan Vega <danvega@gmail.com>
0.1, April 14, 2018
:toc: left
:icons: font
:quick-uri: http://www.therealdanvega.com/spring-boot-2

This is the documentation for my course titled "Getting Started with Spring Boot 2". This documentation will be a central
repository for a lot of the course details.

== Course Details
include::_courseDetails.adoc[]

== Github
include::_github.adoc[]

== Development Environment
include::_developmentEnv.adoc[]

== What's new in Spring

=== Spring Framework 5
include::_whatsnew_springfw5.adoc[]

=== Spring Boot 2
include::_whatsnew_springboot2.adoc[]

== Spring Boot Essentials

=== Actuator

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
```

```
# open up all of the endpoints for demo purposes
# only expose certain endpoints ["health","info"]
management.endpoints.web.expose=*
management.endpoints.web.exclude=env
management.endpoint.health.show-details=true
```

== Resources
include::_resources.adoc[]

== Join our Community

We have started a brand new community for Spring Boot Developers. I want to invite all of you to a new private
Facebook community that I recently started. This is a place for developers to talk about projects that they are
working on, share new tips and tricks and even get help with problems that they are running into in their day to day
development. I will be sharing some of my favorite books, courses and tutorials that will help you sharpen your
Spring Development skills. This should be a fun place for all of us to hang out, so head on over and sign up.
I can’t wait to chat with you!

https://www.facebook.com/groups/157072618416340/

== Contact Me
Dan Vega +
danvega@gmail.com +
http://www.therealdanvega.com +

*Social Media*

http://www.facebook.com/therealdanvega[Facebook] |
http://www.twitter.com/therealdanvega[Twitter] |
http://www.instagram.com/thedanvega[Instagram] |
http://www.youtube.com/therealdanvega/[YouTube] |
https://www.linkedin.com/in/danvega/[LinkedIn] |
https://github.com/cfaddict/[Github]
